apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alpine-app
  template:
    metadata:
      labels:
        app: alpine-app
    spec:
      containers:
        - name: alpine
          image: alpine:latest
          command: ["/bin/sh","-c","while true; do sleep 3600; done"]
---
apiVersion: v1
kind: Service
metadata:
  name: alpine-app
spec:
  selector:
    app: alpine-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

