apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-app
  namespace: gitops
  labels:
    app: jenkins-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins-app
  template:
    metadata:
      labels:
        app: jenkins-app
    spec:
      containers:
      - name: jenkins-app
        image: rabdelrahman3332/jenkins-app:3
        ports:
        - containerPort: 9090
          name: http-port
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-app
  namespace: gitops
  labels:
    app: jenkins-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9090
      protocol: TCP
      name: http
  selector:
    app: jenkins-app
